development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: posts_app_development
  pool: 5
  username: yovan
  password: "ab6307sn"
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: posts_app_test
  pool: 5
  username: yovan
  password: "ab6307sn"
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: posts_app_production
  pool: 5
  username: yovan
  password: "ab6307sn"
  host: localhost
